################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
DDL/workspace_kk/.metadata/.plugins/org.eclipse.cdt.make.core \
DDL/workspace_kk/CMSIS_CORE_LPC8xx/src \
DDL/workspace_kk/Lab3_DDL/Debug/src \
DDL/workspace_kk/Lab3_DDL/src \
DDL/workspace_kk/adc/Debug/cmsis \
DDL/workspace_kk/adc/Debug/driver \
DDL/workspace_kk/adc/Debug/src \
DDL/workspace_kk/adc/Debug/startup \
DDL/workspace_kk/adc/cmsis \
DDL/workspace_kk/adc/driver \
DDL/workspace_kk/adc/src \
DDL/workspace_kk/adc/startup \
DDL/workspace_kk/asm_xample11/Debug \
DDL/workspace_kk/asm_xample11/src \
DDL/workspace_kk/blinky/Debug/cmsis \
DDL/workspace_kk/blinky/Debug/driver \
DDL/workspace_kk/blinky/Debug/src \
DDL/workspace_kk/blinky/Debug/startup \
DDL/workspace_kk/blinky/cmsis \
DDL/workspace_kk/blinky/driver \
DDL/workspace_kk/blinky/src \
DDL/workspace_kk/blinky/startup \
DDL/workspace_kk/common/cmsis \
DDL/workspace_kk/common/driver \
DDL/workspace_kk/common/startup \
DDL/workspace_kk/extint/Debug/cmsis \
DDL/workspace_kk/extint/Debug/driver \
DDL/workspace_kk/extint/Debug/src \
DDL/workspace_kk/extint/Debug/startup \
DDL/workspace_kk/extint/cmsis \
DDL/workspace_kk/extint/driver \
DDL/workspace_kk/extint/src \
DDL/workspace_kk/extint/startup \
DDL/workspace_kk/freertos/Debug/cmsis \
DDL/workspace_kk/freertos/Debug/config \
DDL/workspace_kk/freertos/Debug/driver \
DDL/workspace_kk/freertos/Debug/freertos/port/lpcxpresso/m0 \
DDL/workspace_kk/freertos/Debug/freertos/port/memmang \
DDL/workspace_kk/freertos/Debug/freertos/src \
DDL/workspace_kk/freertos/Debug/src \
DDL/workspace_kk/freertos/cmsis \
DDL/workspace_kk/freertos/config \
DDL/workspace_kk/freertos/driver \
DDL/workspace_kk/freertos/freertos/port/lpcxpresso/m0 \
DDL/workspace_kk/freertos/freertos/port/memmang \
DDL/workspace_kk/freertos/freertos/src \
DDL/workspace_kk/freertos/src \
DDL/workspace_kk/i2c/Debug/cmsis \
DDL/workspace_kk/i2c/Debug/driver \
DDL/workspace_kk/i2c/Debug/src \
DDL/workspace_kk/i2c/Debug/startup \
DDL/workspace_kk/i2c/cmsis \
DDL/workspace_kk/i2c/driver \
DDL/workspace_kk/i2c/src \
DDL/workspace_kk/i2c/startup \
DDL/workspace_kk/i2cslave/Debug/cmsis \
DDL/workspace_kk/i2cslave/Debug/driver \
DDL/workspace_kk/i2cslave/Debug/src \
DDL/workspace_kk/i2cslave/Debug/startup \
DDL/workspace_kk/i2cslave/cmsis \
DDL/workspace_kk/i2cslave/driver \
DDL/workspace_kk/i2cslave/src \
DDL/workspace_kk/i2cslave/startup \
DDL/workspace_kk/intpriority/Debug/cmsis \
DDL/workspace_kk/intpriority/Debug/config \
DDL/workspace_kk/intpriority/Debug/driver \
DDL/workspace_kk/intpriority/Debug/src \
DDL/workspace_kk/intpriority/cmsis \
DDL/workspace_kk/intpriority/config \
DDL/workspace_kk/intpriority/driver \
DDL/workspace_kk/intpriority/src \
DDL/workspace_kk/invokeisp/Debug/cmsis \
DDL/workspace_kk/invokeisp/Debug/driver \
DDL/workspace_kk/invokeisp/Debug/src \
DDL/workspace_kk/invokeisp/Debug/startup \
DDL/workspace_kk/invokeisp/cmsis \
DDL/workspace_kk/invokeisp/driver \
DDL/workspace_kk/invokeisp/src \
DDL/workspace_kk/invokeisp/startup \
DDL/workspace_kk/lib_small_printf_m0/Lib/src \
DDL/workspace_kk/lib_small_printf_m0/src \
DDL/workspace_kk/power_api_demo/Debug/cmsis \
DDL/workspace_kk/power_api_demo/Debug/driver \
DDL/workspace_kk/power_api_demo/Debug/src \
DDL/workspace_kk/power_api_demo/Debug/startup \
DDL/workspace_kk/power_api_demo/cmsis \
DDL/workspace_kk/power_api_demo/driver \
DDL/workspace_kk/power_api_demo/src \
DDL/workspace_kk/power_api_demo/startup \
DDL/workspace_kk/pwm/Debug/cmsis \
DDL/workspace_kk/pwm/Debug/driver \
DDL/workspace_kk/pwm/Debug/src \
DDL/workspace_kk/pwm/Debug/startup \
DDL/workspace_kk/pwm/cmsis \
DDL/workspace_kk/pwm/driver \
DDL/workspace_kk/pwm/src \
DDL/workspace_kk/pwm/startup \
DDL/workspace_kk/rs485/Debug/cmsis \
DDL/workspace_kk/rs485/Debug/driver \
DDL/workspace_kk/rs485/Debug/src \
DDL/workspace_kk/rs485/Debug/startup \
DDL/workspace_kk/rs485/cmsis \
DDL/workspace_kk/rs485/driver \
DDL/workspace_kk/rs485/src \
DDL/workspace_kk/rs485/startup \
DDL/workspace_kk/ssp/Debug/cmsis \
DDL/workspace_kk/ssp/Debug/driver \
DDL/workspace_kk/ssp/Debug/src \
DDL/workspace_kk/ssp/Debug/startup \
DDL/workspace_kk/ssp/cmsis \
DDL/workspace_kk/ssp/driver \
DDL/workspace_kk/ssp/src \
DDL/workspace_kk/ssp/startup \
DDL/workspace_kk/stackusage/Debug/cmsis \
DDL/workspace_kk/stackusage/Debug/config \
DDL/workspace_kk/stackusage/Debug/driver \
DDL/workspace_kk/stackusage/Debug/src \
DDL/workspace_kk/stackusage/cmsis \
DDL/workspace_kk/stackusage/config \
DDL/workspace_kk/stackusage/driver \
DDL/workspace_kk/stackusage/src \
DDL/workspace_kk/stackusage/startup \
DDL/workspace_kk/swuart/Debug/cmsis \
DDL/workspace_kk/swuart/Debug/driver \
DDL/workspace_kk/swuart/Debug/src \
DDL/workspace_kk/swuart/Debug/startup \
DDL/workspace_kk/swuart/cmsis \
DDL/workspace_kk/swuart/driver \
DDL/workspace_kk/swuart/src \
DDL/workspace_kk/swuart/startup \
DDL/workspace_kk/systick/Debug/cmsis \
DDL/workspace_kk/systick/Debug/driver \
DDL/workspace_kk/systick/Debug/src \
DDL/workspace_kk/systick/Debug/startup \
DDL/workspace_kk/systick/cmsis \
DDL/workspace_kk/systick/driver \
DDL/workspace_kk/systick/src \
DDL/workspace_kk/systick/startup \
DDL/workspace_kk/template/src \
DDL/workspace_kk/test/src \
DDL/workspace_kk/timedwakeup/Debug/cmsis \
DDL/workspace_kk/timedwakeup/Debug/driver \
DDL/workspace_kk/timedwakeup/Debug/src \
DDL/workspace_kk/timedwakeup/Debug/startup \
DDL/workspace_kk/timedwakeup/cmsis \
DDL/workspace_kk/timedwakeup/driver \
DDL/workspace_kk/timedwakeup/src \
DDL/workspace_kk/timedwakeup/startup \
DDL/workspace_kk/uart/Debug/cmsis \
DDL/workspace_kk/uart/Debug/driver \
DDL/workspace_kk/uart/Debug/src \
DDL/workspace_kk/uart/Debug/startup \
DDL/workspace_kk/uart/cmsis \
DDL/workspace_kk/uart/driver \
DDL/workspace_kk/uart/src \
DDL/workspace_kk/uart/startup \
DDL/workspace_kk/utilities_lib/src \
DDL/workspace_kk/wdt/Debug/cmsis \
DDL/workspace_kk/wdt/Debug/driver \
DDL/workspace_kk/wdt/Debug/src \
DDL/workspace_kk/wdt/Debug/startup \
DDL/workspace_kk/wdt/cmsis \
DDL/workspace_kk/wdt/driver \
DDL/workspace_kk/wdt/src \
DDL/workspace_kk/wdt/startup \
cmsis \
driver \
src \
startup \

